name: OblivionRelics
version: 1.0.0
main: me.oblivion.relics.OblivionRelics
api-version: '1.21'

author: Oblivion
description: Custom Relic System for Oblivion SMP

commands:
  relictest:
    description: Tests the OblivionRelics plugin
    usage: /relictest

  relicinfo:
    description: Opens the Relic information menu
    usage: /relicinfo

  withdraw:
    description: Withdraws one Echo Flask
    usage: /withdraw

  trust:
    description: Manage trusted players
    usage: /trust <add|remove|list> [player]

  relicgive:
    description: Gives a specific Relic to a player
    usage: /relicgive <player> <relic>
    
  relicstart:
    description: Starts the Oblivion Relic awakening
    usage: /relicstart

  relicinfo:
    description: Opens the Oblivion Relics information menu
    usage: /relicinfo
